columns:
  - LIMIT_BAL: int
  -	SEX: int
  -	EDUCATION: int
  -	MARRIAGE: int
  -	AGE: int
  -	PAY_0: int
  -	PAY_1: int
  -	PAY_2: int
  -	PAY_3: int
  -	PAY_4: int
  -	PAY_5: int
  -	BILL_AMT1: int
  -	BILL_AMT2: int
  -	BILL_AMT3: int
  -	BILL_AMT4: int
  -	BILL_AMT5: int
  -	BILL_AMT6: int
  -	PAY_AMT1: int
  -	PAY_AMT2: int
  -	PAY_AMT3: int
  -	PAY_AMT4: int
  -	PAY_AMT5: int
  - PAY_AMT6: int
  -	class: int

numerical_columns:
  - LIMIT_BAL
  - AGE
  - BILL_AMT1
  - BILL_AMT2
  - BILL_AMT3
  - BILL_AMT4
  - BILL_AMT5
  - BILL_AMT6
  - PAY_AMT1
  - PAY_AMT2
  - PAY_AMT3
  - PAY_AMT4
  - PAY_AMT5
  - PAY_AMT6


binary_columns:
  - SEX

target_column: class
