columns:
  - LIMIT_BAL: float64
  - SEX: float64
  - EDUCATION: float64
  - MARRIAGE: float64
  - AGE: float64
  - PAY_0: float64
  - PAY_1: float64
  - PAY_2: float64
  - PAY_3: float64
  - PAY_4: float64
  - PAY_5: float64
  - BILL_AMT1: float64
  - BILL_AMT2: float64
  - BILL_AMT3: float64
  - BILL_AMT4: float64
  - BILL_AMT5: float64
  - BILL_AMT6: float64
  - PAY_AMT1: float64
  - PAY_AMT2: float64
  - PAY_AMT3: float64
  - PAY_AMT4: float64
  - PAY_AMT5: float64
  - PAY_AMT6: float64
  - class: float64


numerical_columns:
  - LIMIT_BAL
  - AGE
  - BILL_AMT1
  - BILL_AMT2
  - BILL_AMT3
  - BILL_AMT4
  - BILL_AMT5
  - BILL_AMT6
  - PAY_AMT1
  - PAY_AMT2
  - PAY_AMT3
  - PAY_AMT4
  - PAY_AMT5
  - PAY_AMT6


binary_columns:
  - SEX

target_column: class
